process.env.NODE_ENV = process.env.NODE_ENV ?? "test"
process.env.MONGODB_URI = process.env.MONGODB_URI ?? "mongodb://localhost:27017/auth-heavy-saas-test"
process.env.REDIS_ENABLED = process.env.REDIS_ENABLED ?? "false"
process.env.JWT_ACCESS_SECRET = process.env.JWT_ACCESS_SECRET ?? "test-access-secret"
process.env.JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET ?? "test-refresh-secret"
